### ISSUE TITLE
Restyling

### ISSUE THREAD

**Issue by marianobe** [glasperfan/explorer#1]
![I made some restyling](https://user-images.githubusercontent.com/45293664/82051214-d702dc00-968f-11ea-825d-4691167a4120.png)

**Comment by glasperfan** [comment]
Hey @marianobastita that design looks much better than the current one. I didn't put any time into the initial table style, as you can probably tell. Is this something you'd like to contribute a PR for? Otherwise happy to help with implementation - those resource images would be useful

**Comment by marianobe** [comment]
@glasperfan I don't know how to code or use github  :/. I'm just an ux&ui designer.
I have a Figma file if you want it.
It will awesome to add dice roll history, like [colonist-dice-extension](https://github.com/karanmhatre1/colonist-dice-extension).

**Comment by glasperfan** [comment]
Noted. Well thanks for taking the time to engage here!
The Figma file would be useful if it has PNGs or JPGs of the resource cards - I can import those into the extension.

**Comment by glasperfan** [comment]
Actually, I can leverage the game SVGs. I'll try building your design

**Comment by marianobe** [comment]
I just send you an email
